---
title: "genetic_correlations"
output: html_document
---

```{r setup}
rerun_MCMC <- TRUE #(WAS FALSE)

set.seed(224819)

library(MCMCglmm)
library(tidyverse)
library(parallel)
library(cowplot)
library(knitr)

source("color_map.R")
source("ggplot_theme.R")
```


```{r}
h2prot <- read.table("../processed_data/protdat_formatted.txt",
                    sep = '\t',
                    dec = ".", header = TRUE,
                    stringsAsFactors = FALSE)

# Standardize amt_prot
h2prot$amt_prot <- as.numeric(scale(h2prot$amt_prot))

h2prot$animal <- seq(1, nrow(h2prot))
h2prot$treat <- as.factor(h2prot$treat)

h2prot$newS<-c("S")
h2prot$newD<-c("D")
h2prot$sireid <- paste(h2prot$newS,h2prot$sireid)
h2prot$damid <- paste(h2prot$newD,h2prot$damid)

pedigree <- h2prot[, c("animal", "sireid", "damid")]
names(pedigree) <- c("animal", "sire", "dam")
pedigree$animal <- as.character(pedigree$animal)
pedigree$sire <- as.character(pedigree$sire)
pedigree$dam <- as.character(pedigree$dam)

sires <- data.frame(animal = unique(pedigree$sire),
                    sire = NA, dam = NA, stringsAsFactors = FALSE)
dams <- data.frame(animal = unique(pedigree$dam),
                   sire = NA, dam = NA, stringsAsFactors = FALSE)
pedigree <- bind_rows(sires, dams, pedigree) %>%
  as.data.frame()

genet_corr <- tibble(model = character(),
                     HS_C = numeric(),
                     DR_C = numeric(),
                     HS_DR = numeric(),
                     n_eff = numeric())

iter <- 6.5e6
burnin <- 5e4
thinning <-500
chains <- 12
```

## Multivariate analysis

```{r MANOVA_Models, cache=TRUE}
if (rerun_MCMC) {
  HS <- h2prot %>% 
    filter(treat == "HS") %>% rename(prot_HS = amt_prot) %>% 
    as.data.frame()
  DR <- h2prot %>% 
    filter(treat == "DR") %>% rename(prot_DR = amt_prot) %>% 
    as.data.frame()
  STD <- h2prot %>%
    filter(treat == "C") %>% rename(prot_C = amt_prot) %>% 
    as.data.frame()
  
  h2prot_mrg <- full_join(full_join(HS, DR), STD)
  
  prior1 <- list(R = list(V = diag(3) * 1.002, nu = 1.002),
                 G = list(G1 = list(V = diag(3) * 1.002, nu = 0.002)))
  
  priors <- list(prior1)
  prior_names <- c("Tri: V = diag(3) * 1.002, nu = 0.02")
  
  for (ii in 1:length(priors)) {
    prior <- priors[[ii]]
    fm <- mclapply(1:chains, function(i) {
      MCMCglmm(cbind(prot_C, prot_HS, prot_DR) ~ trait - 1,
               random = ~ us(trait):animal,
               rcov = ~ idh(trait):units,
               data = h2prot_mrg,
               prior = prior,
               pedigree = pedigree,
               family = rep("gaussian", 3),
               nitt = iter,
               burnin = burnin,
               thin = thinning)
    }, mc.cores = chains)
    outfile <- paste0("../processed_data/prot_total_multivariate_model_prior", ii, ".Rda")
    save(fm, file = outfile)
    
    re <- lapply(fm, function(m) m$VCV)
    re <- do.call(mcmc.list, re)
    re <- as.mcmc(as.matrix(re))
    
    n_eff <- effectiveSize(re)
    
    # STD vs. HS
    HS_C <- re[ , "traitprot_HS:traitprot_C.animal"] /
      sqrt(re[ , "traitprot_C:traitprot_C.animal"] *
             re[ , "traitprot_HS:traitprot_HS.animal"])
    
    # STD vs. DR
    DR_C <- re[ , "traitprot_DR:traitprot_C.animal"] /
      sqrt(re[ , "traitprot_C:traitprot_C.animal"] *
             re[ , "traitprot_DR:traitprot_DR.animal"])
    
    # DR vs. HS
    HS_DR <- re[ , "traitprot_HS:traitprot_DR.animal"] /
      sqrt(re[ , "traitprot_DR:traitprot_DR.animal"] *
             re[ , "traitprot_HS:traitprot_HS.animal"])
    
    genet_corr <- bind_rows(genet_corr,
                            tibble(model = prior_names[[ii]],
                                   HS_C = median(HS_C),
                                   DR_C = median(DR_C),
                                   HS_DR = median(HS_DR),
                                   n_eff = mean(n_eff)))
  }
  
  write_csv(genet_corr, path = "../processed_data/Genetic_Correlations_protein.csv")
}
```
#### if its worked continue here

### Analyze model

```{r analyze_multivariate_analysis}
load("../processed_data/prot_total_multivariate_model_prior1.Rda")

fe <- lapply(fm, function(m) m$Sol)
fe <- do.call(mcmc.list, fe)
plot(fe[, 1, drop = FALSE], ask = FALSE)
plot(fe[, 2, drop = FALSE], ask = FALSE)
plot(fe[, 3, drop = FALSE], ask = FALSE)

# Extract random effects, convert to mcmc.list
re <- lapply(fm, function(m) m$VCV)
re <- do.call(mcmc.list, re)

plot(re[, 1, drop = FALSE], ask = FALSE)
plot(re[, 2, drop = FALSE], ask = FALSE)
plot(re[, 3, drop = FALSE], ask = FALSE)

autocorr.diag(re)
effectiveSize(re)

# Concatenate samples
re <- as.mcmc(as.matrix(re))

head(re)

# STD vs. HS
plot(re[ , "traitprot_HS:traitprot_C.animal"])
plot(re[ , "traitprot_C:traitprot_C.animal"])
HS_C <- re[ , "traitprot_HS:traitprot_C.animal"] /
  sqrt(re[ , "traitprot_C:traitprot_C.animal"] *
         re[ , "traitprot_HS:traitprot_HS.animal"])
plot(HS_C)
median(HS_C)
HPDinterval(HS_C)

# STD vs. DR
DR_C <- re[ , "traitprot_DR:traitprot_C.animal"] /
  sqrt(re[ , "traitprot_C:traitprot_C.animal"] *
         re[ , "traitprot_DR:traitprot_DR.animal"])
plot(DR_C)
median(DR_C)
HPDinterval(DR_C)

# DR vs. HS
HS_DR <- re[ , "traitprot_HS:traitprot_DR.animal"] /
  sqrt(re[ , "traitprot_DR:traitprot_DR.animal"] *
         re[ , "traitprot_HS:traitprot_HS.animal"])
plot(HS_DR)
median(HS_DR)
HPDinterval(HS_DR)

save(re, file = "../processed_data/prot_total_multivariate_model_output.Rda")
```

### Plot for paper

```{r}
library(tidyverse)
library(cowplot)

B <- data_frame(`HS vs. STD` = as.numeric(HS_C),
                `DR vs. STD` = as.numeric(DR_C),
                `HS vs. DR` = as.numeric(HS_DR))

B <- as_tibble( B ) %>%  
  select(`HS vs. STD`, `DR vs. STD`, `HS vs. DR`) %>% 
  rename(`HS vs. C` = `HS vs. STD`) %>% 
  rename(`DR vs. C` = `DR vs. STD`) %>% 
  rename(`HS vs. DR` = `HS vs. DR`)

colMeans(B)

B %>% gather(Comparison, value) %>%
  ggplot(aes(value, color = Comparison)) +
  geom_line(stat = "density", size = 1) +
  labs(x = "Genetic Correlation", y = "Density") +
  theme(legend.position = c(0.10, 0.85),
        text = element_text(size = 10),
        legend.text = element_text(size = 10))+
  scale_x_continuous(expand = c(0, 0), limits = c(-1.2, 1.2)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 12)) +
  my_theme

ggsave(last_plot(), file = "../plots/protein_Genetic_Correlation_Plot.pdf",
       width = 4, height = 4)
protein_correlation <- last_plot()
save(protein_correlation, file = "../plots/protein_correlation.Rda")
```
